import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "./ui/navbar";
import { poppins } from "./ui/fonts";
import { MyFooter } from "./ui/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${poppins.className} antialiased bg-white text-black`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
